trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: SnykSecrets

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g snyk
      snyk auth $(SNYK_TOKEN)
    displayName: 'Install and authenticate Snyk'

  - script: snyk test
    displayName: 'Run Snyk Open Source scan'

  - script: snyk code test
    displayName: 'Run Snyk Code scan'
