version: 2.1

jobs:
  snyk:
    docker:
      - image: circleci/python:3.8  # Use a imagem Docker apropriada para sua stack
    steps:
      - checkout  # Faz o checkout do código
      - run:
          name: Instalar o Snyk CLI
          command: |
            # Atualiza o npm e instala o Snyk CLI globalmente
            npm install -g snyk
      - run:
          name: Rodar o teste de vulnerabilidades do Snyk
          command: snyk test  # Executa o comando de verificação de vulnerabilidades

workflows:
  version: 2
  snyk-check:
    jobs:
      - snyk:
          filters:
            branches:
              only:
                - main  # Rodar apenas para a branch main
                - master  # Também na branch master
