version: 2.1

# Usando o orb certificado 'snyk-cli'
orbs:
  snyk: snyk/snyk-cli@2.0.0  # Certifique-se de usar a versão mais recente ou disponível

jobs:
  snyk:
    docker:
      - image: circleci/python:3.8  # Use a imagem Docker apropriada para sua stack
    steps:
      - checkout  # Faz o checkout do código
      - run:
          name: Instalar o Snyk
          command: npm install -g snyk  # Instala o cliente Snyk globalmente
      - run:
          name: Rodar o teste de vulnerabilidade do Snyk
          command: snyk test  # Rodar a verificação de vulnerabilidades do Snyk

workflows:
  version: 2
  snyk-check:
    jobs:
      - snyk:
          filters:
            branches:
              only:
                - main  # Filtra para rodar apenas nas branches main
                - master
