version: 2.1

jobs:
  snyk:
    docker:
      - image: cimg/python:3.8  # Imagem base para o pipeline
    steps:
      - checkout

      - run:
          name: Instalar Node.js e npm
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
            sudo apt-get install -y nodejs
            sudo npm install -g npm@latest

      - run:
          name: Instalar dependências do projeto
          command: |
            if [ -f package.json ]; then npm install; fi

      - run:
          name: Instalar o Snyk CLI
          command: sudo npm install -g snyk

      - run:
          name: Configurar endpoint (opcional, depende do seu Snyk)
          command: snyk config set endpoint=https://api.us.snyk.io

      - run:
          name: Autenticar no Snyk
          command: snyk auth $SNYK_TOKEN

      # 1. Teste Open Source (dependências do projeto)
      - run:
          name: Snyk Open Source Scan
          command: snyk test --all-projects || true

      # 2. Teste de Código Estático (Snyk Code / SAST)
      - run:
          name: Snyk Code Scan (SAST)
          command: snyk code test || true

      # 3. Teste de IaC (Terraform, CloudFormation, K8s)
      - run:
          name: Snyk IaC Scan
          command: snyk iac test || true

      # 4. Teste de Containers (imagens Docker)
      - run:
          name: Snyk Container Scan
          command: |
            if [ -f Dockerfile ]; then
              snyk container test . --file=Dockerfile || true
            else
              echo "Nenhum Dockerfile encontrado, pulando scan de container."
            fi

workflows:
  version: 2
  snyk-check:
    jobs:
      - snyk:
          filters:
            branches:
              only:
                - main
                - master
